In [1]:
from modules.preprocessing import WeatherPreprocessor, process_and_merge
from modules.data_loader import load_traffic_data

In [2]:
wp = WeatherPreprocessor()
tdf = load_traffic_data()

📂 Found 8 traffic files. Loading...

/Users/amir/Development/Edu/Reading University  Postgraduate Courses/CSMAD  25-6 Applied Data Science with Python S1 /Course work/Course Work 2/02_csmad_cw2/modules/data_loader.py:60: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  raw_df['timestamp'] = pd.to_datetime(

✅ Traffic Data Loaded. Rows: 123072
   Timeframe: 2021-01-27 00:00:00 to 2024-07-31 23:45:00

In [3]:
raw = wp.load_raw()
print("RAW:", len(raw), raw.index.min(), raw.index.max())

sel = wp.select_columns(raw)
print("SELECTED:", len(sel))

dec = wp.decode(sel)
print("DECODED:", len(dec))

res = wp.resample(dec)
print("RESAMPLED:", len(res), res.index.min(), res.index.max())

RAW: 86824 2021-01-01 00:00:00 2024-09-08 21:20:00
SELECTED: 86824
DECODED: 86824
RESAMPLED: 129302 2021-01-01 00:00:00 2024-09-08 21:15:00

In [4]:
wdf = wp.run()
wdf.head()

,temperature_C,dewpoint_C,rel_humidity,wind_dir_deg,wind_speed_ms,visibility_m,pressure_hPa,precip_mm,ceiling_m,low_ceiling_flag,cloud_oktas,cloud_pct,obscuration_code,obscuration_type,fog_flag,snow_depth_mm,snow_flag,rain_flag,ceiling_category
timestamp,,,,,,,,,,,,,,,,,,,
2021-01-01 00:00:00,-1.00,-1.30,97.827639,330.0,2.10,100.0,1009.60,0.0,600.0,0.0,8.0,100.0,0.0,none,0.0,2.0,1.0,0.0,NaN
2021-01-01 00:15:00,-1.05,-1.35,97.826751,335.0,1.95,125.0,1009.65,0.0,600.0,0.0,8.0,100.0,0.0,none,0.0,2.0,1.0,0.0,NaN
2021-01-01 00:30:00,-1.10,-1.40,97.825861,340.0,1.80,150.0,1009.70,0.0,600.0,0.0,8.0,100.0,0.0,none,0.0,2.0,1.0,0.0,NaN
2021-01-01 00:45:00,-1.15,-1.45,97.824972,345.0,1.65,175.0,1009.75,0.0,600.0,0.0,8.0,100.0,0.0,none,0.0,2.0,1.0,0.0,NaN
2021-01-01 01:00:00,-1.20,-1.50,97.824082,350.0,1.50,200.0,1009.80,0.0,600.0,0.0,8.0,100.0,0.0,none,0.0,2.0,1.0,0.0,NaN

In [5]:
wdf.isnull().sum()
wdf.info()
wdf.nunique()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 129302 entries, 2021-01-01 00:00:00 to 2024-09-08 21:15:00
Freq: 15min
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   temperature_C     129302 non-null  float64
 1   dewpoint_C        129302 non-null  float64
 2   rel_humidity      129302 non-null  float64
 3   wind_dir_deg      129302 non-null  float64
 4   wind_speed_ms     129302 non-null  float64
 5   visibility_m      129302 non-null  float64
 6   pressure_hPa      129302 non-null  float64
 7   precip_mm         129302 non-null  float64
 8   ceiling_m         129302 non-null  float64
 9   low_ceiling_flag  129302 non-null  float64
 10  cloud_oktas       129302 non-null  float64
 11  cloud_pct         129302 non-null  float64
 12  obscuration_code  129302 non-null  float64
 13  obscuration_type  129302 non-null  object
 14  fog_flag          129302 non-null  float64
 15  snow_depth_mm     129302 non-null  float64
 16  snow_flag         129302 non-null  float64
 17  rain_flag         129302 non-null  float64
 18  ceiling_category  129270 non-null  category
dtypes: category(1), float64(17), object(1)
memory usage: 18.9+ MB

temperature_C        4830
dewpoint_C           4325
rel_humidity        89824
wind_dir_deg         1924
wind_speed_ms        2341
visibility_m         2491
pressure_hPa         6577
precip_mm              40
ceiling_m            4406
low_ceiling_flag        2
cloud_oktas             1
cloud_pct               1
obscuration_code        3
obscuration_type        3
fog_flag                1
snow_depth_mm        1165
snow_flag               2
rain_flag               2
ceiling_category        4
dtype: int64

In [6]:
tdf.head()

            timestamp  total_volume  avg_mph
0 2021-01-27 00:00:00           0.0      NaN
1 2021-01-27 00:15:00           0.0      NaN
2 2021-01-27 00:30:00           0.0      NaN
3 2021-01-27 00:45:00           0.0      NaN
4 2021-01-27 01:00:00           0.0      NaN

In [7]:
merged_df = process_and_merge(traffic_df=tdf,weather_df=wdf)

In [8]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 123072 entries, 2021-01-27 00:00:00 to 2024-07-31 23:45:00
Freq: 15min
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   total_volume      123072 non-null  float64
 1   avg_mph           114687 non-null  float64
 2   temperature_C     123072 non-null  float64
 3   dewpoint_C        123072 non-null  float64
 4   rel_humidity      123072 non-null  float64
 5   wind_dir_deg      123072 non-null  float64
 6   wind_speed_ms     123072 non-null  float64
 7   visibility_m      123072 non-null  float64
 8   pressure_hPa      123072 non-null  float64
 9   precip_mm         123072 non-null  float64
 10  ceiling_m         123072 non-null  float64
 11  low_ceiling_flag  123072 non-null  float64
 12  cloud_oktas       123072 non-null  float64
 13  cloud_pct         123072 non-null  float64
 14  obscuration_code  123072 non-null  float64
 15  obscuration_type  123072 non-null  object
 16  fog_flag          123072 non-null  float64
 17  snow_depth_mm     123072 non-null  float64
 18  snow_flag         123072 non-null  float64
 19  rain_flag         123072 non-null  float64
 20  ceiling_category  123072 non-null  category
dtypes: category(1), float64(19), object(1)
memory usage: 19.8+ MB

In [13]:
from modules.timeseries import check_stationarity

df = merged_df.copy()

In [12]:
result = check_stationarity(df["total_volume"])
print(result)

{'ADF Statistic': np.float64(-22.57939055916456), 'p-value': 0.0, 'Critical Values': {'1%': np.float64(-3.4304031665824755), '5%': np.float64(-2.861563498844915), '10%': np.float64(-2.5667825076044326)}, 'Stationary': True}

In [16]:
from modules.timeseries import ARIMAModel
model = ARIMAModel(order=(2,1,2))
model.fit(df["total_volume"])
forecast = model.forecast(48)

In [17]:
forecast

2024-08-01 00:00:00    1.022222e-320
2024-08-01 00:15:00    1.319155e-320
2024-08-01 00:30:00    1.939208e-320
2024-08-01 00:45:00    2.607184e-320
2024-08-01 01:00:00    3.196605e-320
2024-08-01 01:15:00    3.664485e-320
2024-08-01 01:30:00    4.010331e-320
2024-08-01 01:45:00    4.251929e-320
2024-08-01 02:00:00    4.412006e-320
2024-08-01 02:15:00    4.512796e-320
2024-08-01 02:30:00    4.572578e-320
2024-08-01 02:45:00    4.605680e-320
2024-08-01 03:00:00    4.622478e-320
2024-08-01 03:15:00    4.629889e-320
2024-08-01 03:30:00    4.631865e-320
2024-08-01 03:45:00    4.630877e-320
2024-08-01 04:00:00    4.628407e-320
2024-08-01 04:15:00    4.625937e-320
2024-08-01 04:30:00    4.623960e-320
2024-08-01 04:45:00    4.622478e-320
2024-08-01 05:00:00    4.621490e-320
2024-08-01 05:15:00    4.620502e-320
2024-08-01 05:30:00    4.619514e-320
2024-08-01 05:45:00    4.618526e-320
2024-08-01 06:00:00    4.617538e-320
2024-08-01 06:15:00    4.616549e-320
2024-08-01 06:30:00    4.615561e-320
2024-08-01 06:45:00    4.614573e-320
2024-08-01 07:00:00    4.613585e-320
2024-08-01 07:15:00    4.612597e-320
2024-08-01 07:30:00    4.611609e-320
2024-08-01 07:45:00    4.610621e-320
2024-08-01 08:00:00    4.609632e-320
2024-08-01 08:15:00    4.608644e-320
2024-08-01 08:30:00    4.607656e-320
2024-08-01 08:45:00    4.606668e-320
2024-08-01 09:00:00    4.605680e-320
2024-08-01 09:15:00    4.604692e-320
2024-08-01 09:30:00    4.603704e-320
2024-08-01 09:45:00    4.602716e-320
2024-08-01 10:00:00    4.601727e-320
2024-08-01 10:15:00    4.600739e-320
2024-08-01 10:30:00    4.599751e-320
2024-08-01 10:45:00    4.598763e-320
2024-08-01 11:00:00    4.597775e-320
2024-08-01 11:15:00    4.596787e-320
2024-08-01 11:30:00    4.595799e-320
2024-08-01 11:45:00    4.594811e-320
Freq: 15min, Name: predicted_mean, dtype: float64

In [ ]:
from modules.timeseries import SARIMAModel

sarima = SARIMAModel(
    order=(1,1,1),
    seasonal_order=(0,1,1,96)   # daily seasonality for 15-min intervals
)

sarima.fit(df["total_volume"])
forecast = sarima.forecast(96)